version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypw
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"