# Generated by Django 4.2.11 on 2024-05-15 12:27

from uuid import uuid4
from django.apps.registry import Apps
from django.db import migrations, models
from django.utils.text import slugify

def update_slug_if_empty(apps : Apps, schema_editor):
    Post = apps.get_model("blog.Post")
    post_qs = Post.objects.filter(slug="")
    for post in post_qs:
        post.slug = slugify(post.title, allow_unicode=True)
        post.slug += "-" + uuid4().hex[:8]
    Post.objects.bulk_update(post_qs, ["slug"])
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers_post_slug'),
    ]

    operations = [
        migrations.RunPython(update_slug_if_empty, migrations.RunPython.noop),
        
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
