# Generated by Django 4.2.11 on 2024-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_accesslog_created_at_accesslog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('view_premium_post', 'Can view premium 포스팅')], 'verbose_name': '포스팅', 'verbose_name_plural': '포스팅 목록'},
        ),
    ]
