# Generated by Django 4.2.11 on 2024-05-16 08:55

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_course_student_enrollment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(models.F('student'), models.F('course'), django.db.models.functions.text.Lower('semester'), name='blog_enrollment_uniq'),
        ),
    ]
