# Generated by Django 4.2.11 on 2024-05-15 08:52

import csv
from itertools import islice
from typing import Dict, Iterator, Tuple
from django.apps.registry import Apps
from django.db import migrations

CSV_PATH = "shop/assets/zipcode_DB/서울특별시.txt"

def get_code_and_name_from_csv(zipcode_csv_path: str) -> Iterator[Tuple[str, str]]:
    with open(zipcode_csv_path, "rt", encoding="utf-8-sig") as csvfile:
        csv_reader = csv.DictReader(csvfile, delimiter="|")
        row: Dict
        for row in csv_reader:
            code = row["우편번호"]
            name = "{시도} {시군구} {도로명}".format(**row)
            yield code, name


def add_zipcode_data(apps : Apps, schema_editor):
    ZipCode = apps.get_model("shop", "ZipCode")

    zipcode_list = (
        ZipCode(code=code, name=name)
        for code, name in get_code_and_name_from_csv(CSV_PATH)
    )
    batch_size = 1000
    start, stop = 0, batch_size
    while True:
        batch = list(islice(zipcode_list, start, stop))
        if batch:
            ZipCode.objects.bulk_create(batch)
        else:
            break


def remove_zipcode_data(apps : Apps, schema_editor):
    ZipCode = apps.get_model("shop", "ZipCode")
    ZipCode.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_zipcode_data, remove_zipcode_data)
    ]
