# Generated by Django 4.2.11 on 2024-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_insert_zipcode_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorEmployee',
            fields=[
                ('id', models.IntegerField(db_column='employee_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='employee_first_name', max_length=50)),
                ('last_name', models.CharField(db_column='employee_last_name', max_length=50)),
            ],
            options={
                'db_table': 'junior_employee_view',
                'managed': False,
            },
        ),
    ]
